import { MappedInventoryItem, StoreName, ALL_STORES } from '../types/inventory';

export interface RawWondersoftRow {
  'Product Group': string;
  'Department': string;
  'Class': string;
  'Colour': string;
  'Size': string;
  'Garment': string;
  'EAN Code': string;
  'MRP': number | string;
  'Stock': number | string;
  'Store'?: string;
  'Branch'?: string;
  'Toon Label'?: string;
  'ToonLabel'?: string;
  'Image Path'?: string;
  [key: string]: unknown;
}

export const SAMPLE_WONDERSOFT_DATA: RawWondersoftRow[] = [
  // Exact Trackpant item matching user reference image
  {
    'Product Group': 'Menswear',
    'Department': 'MENS TRACKPANT',
    'Class': 'GM Activewear',
    'Colour': 'Black',
    'Size': 'L',
    'Garment': 'Cotton Poly Blend',
    'EAN Code': '8907701122334',
    'MRP': 770,
    'Stock': 4,
    'Store': 'Koottappalli',
    'Toon Label': '6-TP-001',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'MENS TRACKPANT',
    'Class': 'GM Activewear',
    'Colour': 'Black',
    'Size': 'L',
    'Garment': 'Cotton Poly Blend',
    'EAN Code': '8907701122334',
    'MRP': 770,
    'Stock': 1,
    'Store': 'Kumbakonam',
    'Toon Label': '6-TP-001',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'MENS TRACKPANT',
    'Class': 'GM Activewear',
    'Colour': 'Black',
    'Size': 'L',
    'Garment': 'Cotton Poly Blend',
    'EAN Code': '8907701122334',
    'MRP': 770,
    'Stock': 3,
    'Store': 'Mallur',
    'Toon Label': '6-TP-001',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'MENS TRACKPANT',
    'Class': 'GM Activewear',
    'Colour': 'Black',
    'Size': 'L',
    'Garment': 'Cotton Poly Blend',
    'EAN Code': '8907701122334',
    'MRP': 770,
    'Stock': 1,
    'Store': 'Namakkal',
    'Toon Label': '6-TP-001',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'MENS TRACKPANT',
    'Class': 'GM Activewear',
    'Colour': 'Black',
    'Size': 'L',
    'Garment': 'Cotton Poly Blend',
    'EAN Code': '8907701122334',
    'MRP': 770,
    'Stock': 1,
    'Store': 'Salem',
    'Toon Label': '6-TP-001',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'MENS TRACKPANT',
    'Class': 'GM Activewear',
    'Colour': 'Black',
    'Size': 'L',
    'Garment': 'Cotton Poly Blend',
    'EAN Code': '8907701122334',
    'MRP': 770,
    'Stock': 2,
    'Store': 'Tiruvannamalai',
    'Toon Label': '6-TP-001',
  },

  // 6-G028 Series - Variant 01 (Navy Blue)
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Navy Blue',
    'Size': '38',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567890',
    'MRP': 1499,
    'Stock': 14,
    'Store': 'Salem',
    'Toon Label': '6-G028-01',
    'Image Path': 'D:/Wondersoft/Images/6-G028-01-38.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Navy Blue',
    'Size': '38',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567890',
    'MRP': 1499,
    'Stock': 8,
    'Store': 'Karur',
    'Toon Label': '6-G028-01',
    'Image Path': 'D:/Wondersoft/Images/6-G028-01-38.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Navy Blue',
    'Size': '38',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567890',
    'MRP': 1499,
    'Stock': 6,
    'Store': 'Mallur',
    'Toon Label': '6-G028-01',
    'Image Path': 'D:/Wondersoft/Images/6-G028-01-38.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Navy Blue',
    'Size': '38',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567890',
    'MRP': 1499,
    'Stock': 11,
    'Store': 'Namakkal',
    'Toon Label': '6-G028-01',
    'Image Path': 'D:/Wondersoft/Images/6-G028-01-38.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Navy Blue',
    'Size': '38',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567890',
    'MRP': 1499,
    'Stock': 7,
    'Store': 'Thiruvannamalai',
    'Toon Label': '6-G028-01',
    'Image Path': 'D:/Wondersoft/Images/6-G028-01-38.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Navy Blue',
    'Size': '38',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567890',
    'MRP': 1499,
    'Stock': 18,
    'Store': 'Kootapalli',
    'Toon Label': '6-G028-01',
    'Image Path': 'D:/Wondersoft/Images/6-G028-01-38.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Navy Blue',
    'Size': '38',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567890',
    'MRP': 1499,
    'Stock': 9,
    'Store': 'Kumbakonam',
    'Toon Label': '6-G028-01',
    'Image Path': 'D:/Wondersoft/Images/6-G028-01-38.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Navy Blue',
    'Size': '38',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567890',
    'MRP': 1499,
    'Stock': 45,
    'Store': 'GM Fashions Warehouse',
    'Toon Label': '6-G028-01',
    'Image Path': 'D:/Wondersoft/Images/6-G028-01-38.jpg',
  },

  // 6-G028-01 Size 40
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Navy Blue',
    'Size': '40',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567891',
    'MRP': 1499,
    'Stock': 12,
    'Store': 'Salem',
    'Toon Label': '6-G028-01',
    'Image Path': 'D:/Wondersoft/Images/6-G028-01-40.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Navy Blue',
    'Size': '40',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567891',
    'MRP': 1499,
    'Stock': 15,
    'Store': 'Karur',
    'Toon Label': '6-G028-01',
    'Image Path': 'D:/Wondersoft/Images/6-G028-01-40.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Navy Blue',
    'Size': '40',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567891',
    'MRP': 1499,
    'Stock': 5,
    'Store': 'Mallur',
    'Toon Label': '6-G028-01',
    'Image Path': 'D:/Wondersoft/Images/6-G028-01-40.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Navy Blue',
    'Size': '40',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567891',
    'MRP': 1499,
    'Stock': 9,
    'Store': 'Namakkal',
    'Toon Label': '6-G028-01',
    'Image Path': 'D:/Wondersoft/Images/6-G028-01-40.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Navy Blue',
    'Size': '40',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567891',
    'MRP': 1499,
    'Stock': 10,
    'Store': 'Thiruvannamalai',
    'Toon Label': '6-G028-01',
    'Image Path': 'D:/Wondersoft/Images/6-G028-01-40.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Navy Blue',
    'Size': '40',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567891',
    'MRP': 1499,
    'Stock': 14,
    'Store': 'Kootapalli',
    'Toon Label': '6-G028-01',
    'Image Path': 'D:/Wondersoft/Images/6-G028-01-40.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Navy Blue',
    'Size': '40',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567891',
    'MRP': 1499,
    'Stock': 11,
    'Store': 'Kumbakonam',
    'Toon Label': '6-G028-01',
    'Image Path': 'D:/Wondersoft/Images/6-G028-01-40.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Navy Blue',
    'Size': '40',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567891',
    'MRP': 1499,
    'Stock': 52,
    'Store': 'GM Fashions Warehouse',
    'Toon Label': '6-G028-01',
    'Image Path': 'D:/Wondersoft/Images/6-G028-01-40.jpg',
  },

  // 6-G028-02 (Olive Green) - Size 38, 40, 42
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Olive Green',
    'Size': '38',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567892',
    'MRP': 1499,
    'Stock': 7,
    'Store': 'Salem',
    'Toon Label': '6-G028-02',
    'Image Path': 'D:/Wondersoft/Images/6-G028-02-38.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Olive Green',
    'Size': '38',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567892',
    'MRP': 1499,
    'Stock': 12,
    'Store': 'Karur',
    'Toon Label': '6-G028-02',
    'Image Path': 'D:/Wondersoft/Images/6-G028-02-38.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Olive Green',
    'Size': '38',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567892',
    'MRP': 1499,
    'Stock': 4,
    'Store': 'Mallur',
    'Toon Label': '6-G028-02',
    'Image Path': 'D:/Wondersoft/Images/6-G028-02-38.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Olive Green',
    'Size': '38',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567892',
    'MRP': 1499,
    'Stock': 16,
    'Store': 'Kootapalli',
    'Toon Label': '6-G028-02',
    'Image Path': 'D:/Wondersoft/Images/6-G028-02-38.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Olive Green',
    'Size': '38',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567892',
    'MRP': 1499,
    'Stock': 8,
    'Store': 'Namakkal',
    'Toon Label': '6-G028-02',
    'Image Path': 'D:/Wondersoft/Images/6-G028-02-38.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Olive Green',
    'Size': '38',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567892',
    'MRP': 1499,
    'Stock': 5,
    'Store': 'Kumbakonam',
    'Toon Label': '6-G028-02',
    'Image Path': 'D:/Wondersoft/Images/6-G028-02-38.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Olive Green',
    'Size': '38',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567892',
    'MRP': 1499,
    'Stock': 9,
    'Store': 'Thiruvannamalai',
    'Toon Label': '6-G028-02',
    'Image Path': 'D:/Wondersoft/Images/6-G028-02-38.jpg',
  },

  // 6-G028-03 (Wine Red)
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Wine Red',
    'Size': '40',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567893',
    'MRP': 1499,
    'Stock': 10,
    'Store': 'Salem',
    'Toon Label': '6-G028-03',
    'Image Path': 'D:/Wondersoft/Images/6-G028-03-40.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Wine Red',
    'Size': '40',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567893',
    'MRP': 1499,
    'Stock': 14,
    'Store': 'Karur',
    'Toon Label': '6-G028-03',
    'Image Path': 'D:/Wondersoft/Images/6-G028-03-40.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Wine Red',
    'Size': '40',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567893',
    'MRP': 1499,
    'Stock': 12,
    'Store': 'Kootapalli',
    'Toon Label': '6-G028-03',
    'Image Path': 'D:/Wondersoft/Images/6-G028-03-40.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Wine Red',
    'Size': '40',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567893',
    'MRP': 1499,
    'Stock': 6,
    'Store': 'Mallur',
    'Toon Label': '6-G028-03',
    'Image Path': 'D:/Wondersoft/Images/6-G028-03-40.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Wine Red',
    'Size': '40',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567893',
    'MRP': 1499,
    'Stock': 7,
    'Store': 'Namakkal',
    'Toon Label': '6-G028-03',
    'Image Path': 'D:/Wondersoft/Images/6-G028-03-40.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Wine Red',
    'Size': '40',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567893',
    'MRP': 1499,
    'Stock': 8,
    'Store': 'Kumbakonam',
    'Toon Label': '6-G028-03',
    'Image Path': 'D:/Wondersoft/Images/6-G028-03-40.jpg',
  },
  {
    'Product Group': 'Menswear',
    'Department': 'Oxford Casual Shirt',
    'Class': 'GM Signature',
    'Colour': 'Wine Red',
    'Size': '40',
    'Garment': '100% Premium Cotton',
    'EAN Code': '8901234567893',
    'MRP': 1499,
    'Stock': 11,
    'Store': 'Thiruvannamalai',
    'Toon Label': '6-G028-03',
    'Image Path': 'D:/Wondersoft/Images/6-G028-03-40.jpg',
  },

  // 8-M104-01 Series (Denim Straight Fit Jeans)
  {
    'Product Group': 'Denim & Bottoms',
    'Department': 'Straight Fit Stretch Jeans',
    'Class': 'Urban Stitch',
    'Colour': 'Washed Indigo',
    'Size': '32',
    'Garment': 'Cotton Lycra Stretch Denim',
    'EAN Code': '8904567890123',
    'MRP': 2199,
    'Stock': 19,
    'Store': 'Salem',
    'Toon Label': '8-M104-01',
    'Image Path': 'D:/Wondersoft/Images/8-M104-01-32.jpg',
  },
  {
    'Product Group': 'Denim & Bottoms',
    'Department': 'Straight Fit Stretch Jeans',
    'Class': 'Urban Stitch',
    'Colour': 'Washed Indigo',
    'Size': '32',
    'Garment': 'Cotton Lycra Stretch Denim',
    'EAN Code': '8904567890123',
    'MRP': 2199,
    'Stock': 22,
    'Store': 'Karur',
    'Toon Label': '8-M104-01',
    'Image Path': 'D:/Wondersoft/Images/8-M104-01-32.jpg',
  },
  {
    'Product Group': 'Denim & Bottoms',
    'Department': 'Straight Fit Stretch Jeans',
    'Class': 'Urban Stitch',
    'Colour': 'Washed Indigo',
    'Size': '32',
    'Garment': 'Cotton Lycra Stretch Denim',
    'EAN Code': '8904567890123',
    'MRP': 2199,
    'Stock': 14,
    'Store': 'Kootapalli',
    'Toon Label': '8-M104-01',
    'Image Path': 'D:/Wondersoft/Images/8-M104-01-32.jpg',
  },
  {
    'Product Group': 'Denim & Bottoms',
    'Department': 'Straight Fit Stretch Jeans',
    'Class': 'Urban Stitch',
    'Colour': 'Washed Indigo',
    'Size': '32',
    'Garment': 'Cotton Lycra Stretch Denim',
    'EAN Code': '8904567890123',
    'MRP': 2199,
    'Stock': 9,
    'Store': 'Mallur',
    'Toon Label': '8-M104-01',
    'Image Path': 'D:/Wondersoft/Images/8-M104-01-32.jpg',
  },
  {
    'Product Group': 'Denim & Bottoms',
    'Department': 'Straight Fit Stretch Jeans',
    'Class': 'Urban Stitch',
    'Colour': 'Washed Indigo',
    'Size': '32',
    'Garment': 'Cotton Lycra Stretch Denim',
    'EAN Code': '8904567890123',
    'MRP': 2199,
    'Stock': 13,
    'Store': 'Namakkal',
    'Toon Label': '8-M104-01',
    'Image Path': 'D:/Wondersoft/Images/8-M104-01-32.jpg',
  },
  {
    'Product Group': 'Denim & Bottoms',
    'Department': 'Straight Fit Stretch Jeans',
    'Class': 'Urban Stitch',
    'Colour': 'Washed Indigo',
    'Size': '32',
    'Garment': 'Cotton Lycra Stretch Denim',
    'EAN Code': '8904567890123',
    'MRP': 2199,
    'Stock': 17,
    'Store': 'Kumbakonam',
    'Toon Label': '8-M104-01',
    'Image Path': 'D:/Wondersoft/Images/8-M104-01-32.jpg',
  },
  {
    'Product Group': 'Denim & Bottoms',
    'Department': 'Straight Fit Stretch Jeans',
    'Class': 'Urban Stitch',
    'Colour': 'Washed Indigo',
    'Size': '32',
    'Garment': 'Cotton Lycra Stretch Denim',
    'EAN Code': '8904567890123',
    'MRP': 2199,
    'Stock': 12,
    'Store': 'Thiruvannamalai',
    'Toon Label': '8-M104-01',
    'Image Path': 'D:/Wondersoft/Images/8-M104-01-32.jpg',
  },
  {
    'Product Group': 'Denim & Bottoms',
    'Department': 'Straight Fit Stretch Jeans',
    'Class': 'Urban Stitch',
    'Colour': 'Washed Indigo',
    'Size': '32',
    'Garment': 'Cotton Lycra Stretch Denim',
    'EAN Code': '8904567890123',
    'MRP': 2199,
    'Stock': 38,
    'Store': 'GM Fashions Warehouse',
    'Toon Label': '8-M104-01',
    'Image Path': 'D:/Wondersoft/Images/8-M104-01-32.jpg',
  },

  // 8-M104-02 (Black Denim)
  {
    'Product Group': 'Denim & Bottoms',
    'Department': 'Straight Fit Stretch Jeans',
    'Class': 'Urban Stitch',
    'Colour': 'Jet Black',
    'Size': '34',
    'Garment': 'Cotton Lycra Stretch Denim',
    'EAN Code': '8904567890124',
    'MRP': 2299,
    'Stock': 16,
    'Store': 'Salem',
    'Toon Label': '8-M104-02',
    'Image Path': 'D:/Wondersoft/Images/8-M104-02-34.jpg',
  },
  {
    'Product Group': 'Denim & Bottoms',
    'Department': 'Straight Fit Stretch Jeans',
    'Class': 'Urban Stitch',
    'Colour': 'Jet Black',
    'Size': '34',
    'Garment': 'Cotton Lycra Stretch Denim',
    'EAN Code': '8904567890124',
    'MRP': 2299,
    'Stock': 20,
    'Store': 'Karur',
    'Toon Label': '8-M104-02',
    'Image Path': 'D:/Wondersoft/Images/8-M104-02-34.jpg',
  },
  {
    'Product Group': 'Denim & Bottoms',
    'Department': 'Straight Fit Stretch Jeans',
    'Class': 'Urban Stitch',
    'Colour': 'Jet Black',
    'Size': '34',
    'Garment': 'Cotton Lycra Stretch Denim',
    'EAN Code': '8904567890124',
    'MRP': 2299,
    'Stock': 11,
    'Store': 'Kootapalli',
    'Toon Label': '8-M104-02',
    'Image Path': 'D:/Wondersoft/Images/8-M104-02-34.jpg',
  },
  {
    'Product Group': 'Denim & Bottoms',
    'Department': 'Straight Fit Stretch Jeans',
    'Class': 'Urban Stitch',
    'Colour': 'Jet Black',
    'Size': '34',
    'Garment': 'Cotton Lycra Stretch Denim',
    'EAN Code': '8904567890124',
    'MRP': 2299,
    'Stock': 7,
    'Store': 'Mallur',
    'Toon Label': '8-M104-02',
    'Image Path': 'D:/Wondersoft/Images/8-M104-02-34.jpg',
  },
  {
    'Product Group': 'Denim & Bottoms',
    'Department': 'Straight Fit Stretch Jeans',
    'Class': 'Urban Stitch',
    'Colour': 'Jet Black',
    'Size': '34',
    'Garment': 'Cotton Lycra Stretch Denim',
    'EAN Code': '8904567890124',
    'MRP': 2299,
    'Stock': 14,
    'Store': 'Namakkal',
    'Toon Label': '8-M104-02',
    'Image Path': 'D:/Wondersoft/Images/8-M104-02-34.jpg',
  },
  {
    'Product Group': 'Denim & Bottoms',
    'Department': 'Straight Fit Stretch Jeans',
    'Class': 'Urban Stitch',
    'Colour': 'Jet Black',
    'Size': '34',
    'Garment': 'Cotton Lycra Stretch Denim',
    'EAN Code': '8904567890124',
    'MRP': 2299,
    'Stock': 9,
    'Store': 'Kumbakonam',
    'Toon Label': '8-M104-02',
    'Image Path': 'D:/Wondersoft/Images/8-M104-02-34.jpg',
  },
  {
    'Product Group': 'Denim & Bottoms',
    'Department': 'Straight Fit Stretch Jeans',
    'Class': 'Urban Stitch',
    'Colour': 'Jet Black',
    'Size': '34',
    'Garment': 'Cotton Lycra Stretch Denim',
    'EAN Code': '8904567890124',
    'MRP': 2299,
    'Stock': 15,
    'Store': 'Thiruvannamalai',
    'Toon Label': '8-M104-02',
    'Image Path': 'D:/Wondersoft/Images/8-M104-02-34.jpg',
  },

  // 3-K009-01 (Womens Kurta)
  {
    'Product Group': 'Womens Ethnic',
    'Department': 'Chanderi Anarkali Kurta',
    'Class': 'Aura Heritage',
    'Colour': 'Mustard Yellow',
    'Size': 'M',
    'Garment': 'Chanderi Silk Blend',
    'EAN Code': '8906789012345',
    'MRP': 1899,
    'Stock': 12,
    'Store': 'Salem',
    'Toon Label': '3-K009-01',
    'Image Path': 'D:/Wondersoft/Images/3-K009-01-M.jpg',
  },
  {
    'Product Group': 'Womens Ethnic',
    'Department': 'Chanderi Anarkali Kurta',
    'Class': 'Aura Heritage',
    'Colour': 'Mustard Yellow',
    'Size': 'M',
    'Garment': 'Chanderi Silk Blend',
    'EAN Code': '8906789012345',
    'MRP': 1899,
    'Stock': 18,
    'Store': 'Karur',
    'Toon Label': '3-K009-01',
    'Image Path': 'D:/Wondersoft/Images/3-K009-01-M.jpg',
  },
  {
    'Product Group': 'Womens Ethnic',
    'Department': 'Chanderi Anarkali Kurta',
    'Class': 'Aura Heritage',
    'Colour': 'Mustard Yellow',
    'Size': 'M',
    'Garment': 'Chanderi Silk Blend',
    'EAN Code': '8906789012345',
    'MRP': 1899,
    'Stock': 14,
    'Store': 'Kootapalli',
    'Toon Label': '3-K009-01',
    'Image Path': 'D:/Wondersoft/Images/3-K009-01-M.jpg',
  },
  {
    'Product Group': 'Womens Ethnic',
    'Department': 'Chanderi Anarkali Kurta',
    'Class': 'Aura Heritage',
    'Colour': 'Mustard Yellow',
    'Size': 'M',
    'Garment': 'Chanderi Silk Blend',
    'EAN Code': '8906789012345',
    'MRP': 1899,
    'Stock': 8,
    'Store': 'Namakkal',
    'Toon Label': '3-K009-01',
    'Image Path': 'D:/Wondersoft/Images/3-K009-01-M.jpg',
  },
  {
    'Product Group': 'Womens Ethnic',
    'Department': 'Chanderi Anarkali Kurta',
    'Class': 'Aura Heritage',
    'Colour': 'Mustard Yellow',
    'Size': 'M',
    'Garment': 'Chanderi Silk Blend',
    'EAN Code': '8906789012345',
    'MRP': 1899,
    'Stock': 11,
    'Store': 'Kumbakonam',
    'Toon Label': '3-K009-01',
    'Image Path': 'D:/Wondersoft/Images/3-K009-01-M.jpg',
  },
  {
    'Product Group': 'Womens Ethnic',
    'Department': 'Chanderi Anarkali Kurta',
    'Class': 'Aura Heritage',
    'Colour': 'Mustard Yellow',
    'Size': 'M',
    'Garment': 'Chanderi Silk Blend',
    'EAN Code': '8906789012345',
    'MRP': 1899,
    'Stock': 6,
    'Store': 'Mallur',
    'Toon Label': '3-K009-01',
    'Image Path': 'D:/Wondersoft/Images/3-K009-01-M.jpg',
  },
  {
    'Product Group': 'Womens Ethnic',
    'Department': 'Chanderi Anarkali Kurta',
    'Class': 'Aura Heritage',
    'Colour': 'Mustard Yellow',
    'Size': 'M',
    'Garment': 'Chanderi Silk Blend',
    'EAN Code': '8906789012345',
    'MRP': 1899,
    'Stock': 10,
    'Store': 'Thiruvannamalai',
    'Toon Label': '3-K009-01',
    'Image Path': 'D:/Wondersoft/Images/3-K009-01-M.jpg',
  },
  {
    'Product Group': 'Womens Ethnic',
    'Department': 'Chanderi Anarkali Kurta',
    'Class': 'Aura Heritage',
    'Colour': 'Mustard Yellow',
    'Size': 'M',
    'Garment': 'Chanderi Silk Blend',
    'EAN Code': '8906789012345',
    'MRP': 1899,
    'Stock': 25,
    'Store': 'GM Fashions Warehouse',
    'Toon Label': '3-K009-01',
    'Image Path': 'D:/Wondersoft/Images/3-K009-01-M.jpg',
  },
];
